-- SmadProx v2 — Supabase Schema
-- Run this in the Supabase SQL Editor to create the required tables.

-- ─── Candidate Submissions ──────────────────────────────────────────────────
-- Stores data from the submission portal (setup-instructions-smadprox.vercel.app)

CREATE TABLE IF NOT EXISTS candidate_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id TEXT NOT NULL,
  candidate_name TEXT DEFAULT '',
  company TEXT DEFAULT '',
  round_type TEXT DEFAULT '',
  resume TEXT DEFAULT '',
  jd TEXT DEFAULT '',
  interviewer_info TEXT DEFAULT '',
  recruiter_notes TEXT DEFAULT '',
  slot_time TEXT DEFAULT '',
  chrome_remote_desktop TEXT DEFAULT '',
  extra_context JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_submissions_candidate_id ON candidate_submissions(candidate_id);

-- ─── Interview Scripts (generated by script_generator.py) ───────────────────
-- Replaces manual Cursor-generated script.md files

CREATE TABLE IF NOT EXISTS interview_scripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id TEXT NOT NULL,
  submission_id UUID REFERENCES candidate_submissions(id),
  company TEXT DEFAULT '',
  round_type TEXT DEFAULT '',
  script_content TEXT DEFAULT '',
  prompt_hash TEXT DEFAULT '',
  status TEXT DEFAULT 'generating' CHECK (status IN ('generating', 'ready', 'reviewed', 'error')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_scripts_candidate_id ON interview_scripts(candidate_id);
CREATE INDEX IF NOT EXISTS idx_scripts_status ON interview_scripts(status);

-- ─── Auto-update updated_at on modification ─────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_submissions_updated_at
  BEFORE UPDATE ON candidate_submissions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_scripts_updated_at
  BEFORE UPDATE ON interview_scripts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─── Row Level Security (optional — enable if multi-tenant) ─────────────────
-- ALTER TABLE candidate_submissions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE interview_scripts ENABLE ROW LEVEL SECURITY;
